iam.bootstrap.enabled=true

iam.bootstrap.system-admin.subject-id=system-admin
iam.bootstrap.system-admin.subject-type=USER

iam.bootstrap.tenant-admin.tenant-id=tenantA
iam.bootstrap.tenant-admin.subject-id=tenant-admin
iam.bootstrap.tenant-admin.subject-type=USER

iam.swagger.enabled=true
